models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()

from .user import User
from .activityplan import ActivityPlan
from .mealplan import MealPlan

models/activityplan.py
from . import db
from datetime import datetime


class ActivityPlan(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    morning_activity = db.Column(db.String(100))
    afternoon_activity = db.Column(db.String(100))
    evening_activity = db.Column(db.String(100))
    age_category = db.Column(db.String(20))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

models/mealplan.py
from . import db
from datetime import datetime

class MealPlan(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    breakfast = db.Column(db.String(200))
    lunch = db.Column(db.String(200))
    dinner = db.Column(db.String(200))
    region = db.Column(db.String(20))
    bmi_category = db.Column(db.String(50))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    

models/user.py
from . import db
from datetime import datetime


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username= db.Column(db.String(50), unique=True, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at =db.Column(db.DateTime, default=datetime.utcnow)
    age = db.Column(db.String(50), nullable=False)
    region = db.Column(db.String(50), nullable=False)
    bmi = db.Column(db.Integer, nullable=False)
    bmi_category = db.Column(db.String(50), nullable=True)
    activity_plans = db.relationship('ActivityPlan', backref='user', lazy=True)
    meal_plans = db.relationship('MealPlan', backref='user', lazy=True)

    def __repr__(self):
        return f'{self.name}, {self.age}'

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from db_config import DB_URL
from models import db
from flask_migrate import Migrate
from routes.index import index_bp
from routes.home import home_bp
from routes.comefly import comefly
from routes.gofly import gofly
from routes.flystatus import flystatus
from routes.about import about


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(index_bp)
app.register_blueprint(home_bp)
app.register_blueprint(comefly)
app.register_blueprint(flystatus)
app.register_blueprint(gofly)
app.register_blueprint(about)

if __name__ == '__main__':
    app.run(debug=True)

routes/__init__.py
from flask import render_template, request

from models import *

routes/about.py
from flask import Flask, Blueprint, render_template

about = Blueprint('aboutus', __name__)


@about.route('/aboutus',  methods=['GET', 'POST'])
def aboutus(): 
    return render_template('about.html')

routes/admin.py
from flask import Flask, render_template, Blueprint

admin=Blueprint('admin', __name__)

@admin.route('/admin')
def admin_page():
    return render_template('admin.html')

routes/comefly.py
from flask import Flask, Blueprint, render_template

comefly = Blueprint('comefly', __name__)


@comefly.route('/comefly',  methods=['GET', 'POST'])
def come_fly(): 
    return render_template('comefly.html')

routes/createmealplan.py
from flask import Flask, Blueprint, render_template

meal_plan = Blueprint('mealplan', __name__)
@meal_plan.route(/add_meal_plan', methods=['POST'])
    def mealplan():
        return render_template('addmealplan.html')

routes/flystatus.py
from flask import Flask, Blueprint, render_template, request
from sqlalchemy.exc import IntegrityError
from models import db, User, ActivityPlan, MealPlan


from middleware.utils import *

flystatus = Blueprint('flystatus', __name__)

@flystatus.route('/status', methods=['POST'],)
def fly_status():
    try:
        name = request.form['name']
        age = age_group(request.form['age'])
        height = request.form['height']
        weight = request.form['weight']
        region = request.form['region']
        bmi = calculate_bmi(convert_feet_to_inches(height), kg_to_lbs(weight))
        bmi_category = get_bmi_category(bmi)
        user = User(username=name, age=age, region=region, bmi=bmi, bmi_category=bmi_category)

        # Add user to the database session and commit changes
        db.session.add(user)
        db.session.commit()    

        return render_template('status.html', name=name, bmi=bmi, category=bmi_category)  
    except IntegrityError as e:
        # Rollback the session to prevent partially inserted data
        db.session.rollback()
        error_message = f"Username '{name}' already exists. Please choose a different username."
        
        # Return the error message to the client
        return render_template('comefly.html', error_statement=error_message,
                                name=name, age=age, height=height, weight=weight, region=region)
        
    except KeyError:
        # Handle the case where the 'region' key is missing from the form data
        name = request.form.get('name', '')
        age = request.form.get('age', '')
        height = request.form.get('height', '')
        weight = request.form.get('weight', '')
        region = request.form.get('region', '')
        error_statement = 'All Form Fields Required'
        
        return render_template('comefly.html',
                                error_statement=error_statement,
                                name=name,
                                age=age,
                                height=height,
                                weight=weight,
                                region=region)  

routes/gofly.py
from flask import Flask, Blueprint, render_template
from models import db, ActivityPlan, MealPlan, User

gofly = Blueprint('gofly', __name__)

@gofly.route('/gofly/<name>')
def go_fly(name):
    # Retrieve the user based on the provided name
    user = User.query.filter_by(username=name).first()
    meal_plans = user.meal_plans
    
    # If user not found, return an error message
    if not user:
        return "User not found", 404
    
    # Query the ActivityPlan and MealPlan based on user's age category and BMI category
    activity_plan = user.activity_plans
    meal_plan = MealPlan.query.filter_by(bmi_category=user.bmi_category, region=user.region).limit(7).all()
    
    # Render the template with the retrieved data
    return render_template('gofly.html', activity_plan=activity_plan, meal_plan=meal_plan)

routes/home.py
from flask import Flask, Blueprint, render_template

home_bp = Blueprint('home', __name__)

@home_bp.route('/home')
def home():
    return render_template('home.html')

routes/index.py
from flask import Flask, Blueprint, render_template

index_bp = Blueprint('index', __name__)

@index_bp.route('/')
def index():
    return render_template('index.html')

templates/about.html
{% extends 'base.html' %}
{% block title %}
    Home page
{% endblock %}
{% block content %}
    <h1>Welcome to Madefly</h1>
    <p>This app is Inspired by my interest in fitness as I am fitness Enthusiast. Its a great feeling to be able to come up with something like this. I can not but acknowledge ALX as they inspired the conceptualization of this Idea</p> 
    {% endblock %}

templates/admin.html
<h1>Welcome Admin</h1>
<ol>    
    <li><a href="#">update meal plan</a></li>
    <li><a href="#">Update activity plan</a></li>
    <li><a href="#">Add new user</a></li>
    <li><a href="#">Delete a user</a></li>
</ol>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>
  <body>
    <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('home.home') }}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('comefly.come_fly') }}">Comefly <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('aboutus.aboutus') }}"">About us</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Admin login</a>
                </li>
            </ul>
        </div>
      </nav>
    </header>
    <main>
   
    <!-- Future Content here -->
    {% block content %}
    {% endblock %}

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </main>
  </body>
</html>

templates/comefly.html
{% extends 'base.html' %}
{% block title %}
    Onboarding
{% endblock %}
    {% block content %}
    {% if error_statement %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ error_statement }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
    {% endif %}
      <h1>Get onboard!</h1>
      <form action="{{ url_for('flystatus.fly_status') }}" method="POST">
        <label for="name">Name:</label>
          <input type="text" id="name" name="name" value="{{ name }}"><br>
          <label for="age">Age:</label>
          <input type="number" id="age" name="age" value="{{ age }}" step="1" min="0" required><br>
          <label for="height">Height (ft):</label>
          <select id="height-feet" name="height">
            <option value="4">4ft</option>
            <option value="4'5">4'5ft</option>
            <option value="5">5ft</option>
            <option value="5'2">5'2ft</option>
            <option value="5'3">5'3ft</option>
            <option value="5'4">5'4ft</option>
            <option value="5'5">5'5ft</option>
            <option value="5'6">5'6ft</option>
            <option value="5'7">5'7ft</option>
            <option value="5'8">5'8ft</option>
            <option value="6">6ft</option>
            <option value="6'2">6'2ft</option>
            <option value="6'3">6'3ft</option>
            <option value="6'4">6'4ft</option>
            <option value="6'5">6'5ft</option>
        </select><br>
          <label for="weight">Weight (kg):</label>
          <input type="number" id="weight" name="weight" value="{{ weight }}" min="40" required><br>

          <label>Region:</label>
          <input type="radio" id="Africa" name="region" value="Africa">
          <label for="Africa">Africa</label>

          <input type="radio" id="America" name="region" value="America">
          <label for="America">America</label>

          <input type="radio" id="Europe" name="region" value="Europe">
          <label for="Europe">Europe</label><br>
          <input type="submit" value="Submit">
      </form>
    {% endblock %}
  </body>

templates/gofly.html
{% extends 'base.html' %}
{% block title %}
    Ready to fly
{% endblock %}
{% block content %}
    <h1>Ready to fly!</h1>
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <!-- Your Columns HERE -->
                <th scope="col">Id</th>
                <th scope="col">Day</th>
                <th scope="col">Breakfast</th>
                <th scope="col">Lunch</th>
                <th scope="col">Dinner</th>
            </tr>
        </thead>
        <tbody>
            <!-- Your rows inside the table HERE: -->
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.Day }}</td>
                    <td>{{ item.Breakfast }}</td>
                    <td>{{ item.Lunch }}</td>
                    <td>{{ item.Dinner }}</td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
        </tbody>
    </table>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}
    Home page
{% endblock %}
{% block content %}
    <h1>Welcome to Madefly</h1>
    <img id="homejpeg" src="{{url_for('static', filename='images/homepage.jpeg') }}">
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
   Landing page
{% endblock %}
{% block content %}
    <h1>Madefly</h1>
    <div class="images">
        <img id="homejpeg" src="{{url_for('static', filename='images/spreaad.jpeg') }}">
        <img id="homejpeg" src="{{url_for('static', filename='images/387e8a6b2ee43be0c07796b29d52ffca.png') }}">
        <img id="homejpeg" src="{{url_for('static', filename='images/spread2.jpeg') }}">
    </div>
    <p>You can do amazing stuff when you know you can fly</p>
    </br>
    <hr/>
    </br>
    <div class="d-grid gap-2 col-6 mx-auto">
        <a href="{{ url_for('home.home') }}" class="btn btn-secondary" role="button">Join us</a>
    </div>

{% endblock %}

templates/status.html
{% extends 'base.html' %}
{% block title %}
    <title>Fly Status</title>
{% endblock %}

{% block content %}
    <h1>Know your status!</h1>
    <p>Hello, {{ name }}!</p>
    <p>Your BMI is {{ bmi }} and you are {{ category }}.</p>
    <form action="{{ url_for('gofly.go_fly', name=name) }}" method="GET">
        <input type="checkbox" id="agreeCheckbox" onchange="enableButton()"> I agree to get a meal plan and workout activities<br>
        <button type="submit" id="submitButton" disabled>Go fly</button>
    </form>


    <script>
        function enableButton() {
            document.getElementById("submitButton").disabled = !document.getElementById("agreeCheckbox").checked;
        }
    </script>
{% endblock %}